import {copyText,setupEmbedHeight} from '../../assets/play-tools.js?v=0.3.2';
const $=s=>document.querySelector(s), sets={lower:'abcdefghijklmnopqrstuvwxyz',upper:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',number:'0123456789',symbol:'!@#$%^&*()-_=+[]{};:,.?'};
const words=['amber','apple','breeze','cloud','coral','dawn','forest','harbor','island','lemon','maple','moon','ocean','pearl','river','solar','stone','tulip','violet','willow'];
const tr=(ko,en)=>window.ToolboxI18n?.language==='en'?en:ko;let current='',currentBits=0,currentCount=1,statusState='created';
function random(max){const limit=256-256%max,buffer=new Uint8Array(1);do{crypto.getRandomValues(buffer);}while(buffer[0]>=limit);return buffer[0]%max;}
function shuffle(text){const out=[...text];for(let i=out.length-1;i>0;i--){const j=random(i+1);[out[i],out[j]]=[out[j],out[i]];}return out.join('');}
function selected(){return Object.keys(sets).filter(key=>$(`#pw-${key}`).checked).map(key=>sets[key]).map(text=>$('#pw-ambiguous').checked?text.replace(/[0OlI]/g,''):text);}
function renderDetail(){if(!current){$('#pw-detail').textContent='';return;}$('#pw-detail').textContent=tr(`${currentCount}개 생성 · 각 비밀번호 예상 조합 강도 약 ${currentBits}비트 · 서버로 전송되지 않습니다.`,`${currentCount} generated · About ${currentBits} bits per password · Nothing leaves this browser.`);}
function renderStatus(){const states={created:[tr('새 비밀번호를 만들었습니다.','Created a new password.'),'is-good'],groups:[tr('포함할 문자를 하나 이상 선택해 주세요.','Select at least one character group.'),'is-error'],empty:[tr('먼저 비밀번호를 만들어 주세요.','Create a password first.'),'is-error'],copied:[tr('비밀번호를 복사했습니다.','Password copied.'),'is-good'],blocked:[tr('자동 복사가 차단되었습니다. 아래 결과를 선택해 직접 복사해 주세요.','Automatic copying was blocked. Select the result below and copy it manually.'),'']};const state=states[statusState]||states.created;$('#pw-status').textContent=state[0];$('#pw-status').className=`st-status ${state[1]}`;}
function setStatus(state){statusState=state;renderStatus();}
function clearResult(){current='';currentBits=0;$('#pw-result').textContent='';$('#pw-meter').style.width='0%';$('#pw-copy').disabled=true;$('#pw-fallback').hidden=true;renderDetail();}
function makePassword(length,groups,all){return shuffle(groups.map(group=>group[random(group.length)]).join('')+Array.from({length:length-groups.length},()=>all[random(all.length)]).join(''));}
function generate(){const length=Math.max(8,Math.min(64,Number($('#pw-length').value)||20));currentCount=Math.max(1,Math.min(20,Number($('#pw-count').value)||1));$('#pw-length').value=length;$('#pw-range').value=length;$('#pw-count').value=currentCount;$('#pw-count-range').value=currentCount;$('#pw-fallback').hidden=true;const groups=selected();if(!groups.length){clearResult();setStatus('groups');return;}const all=groups.join('');current=Array.from({length:currentCount},()=>makePassword(length,groups,all)).join('\n');currentBits=Math.round(length*Math.log2(all.length));$('#pw-result').textContent=current;$('#pw-meter').style.width=`${Math.min(100,Math.round(currentBits/1.2))}%`;$('#pw-copy').disabled=false;renderDetail();setStatus('created');}
const loginPreset=document.createElement('button');loginPreset.className='st-secondary';loginPreset.id='pw-login-preset';loginPreset.type='button';loginPreset.dataset.ko='16자 로그인 설정';loginPreset.dataset.en='16-character login';loginPreset.textContent=window.ToolboxI18n?.language==='en'?'16-character login':'16자 로그인 설정';$('#pw-safe-preset').before(loginPreset);
loginPreset.addEventListener('click',()=>{$('#pw-length').value=16;$('#pw-range').value=16;$('#pw-count').value=1;$('#pw-count-range').value=1;['lower','upper','number','symbol'].forEach(key=>{$(`#pw-${key}`).checked=true;});$('#pw-ambiguous').checked=true;generate();});
const batchPreset=document.createElement('button');batchPreset.className='st-secondary';batchPreset.id='pw-batch-preset';batchPreset.type='button';batchPreset.dataset.ko='5개 묶음 생성';batchPreset.dataset.en='Generate a batch of 5';batchPreset.textContent=window.ToolboxI18n?.language==='en'?'Generate a batch of 5':'5개 묶음 생성';loginPreset.after(batchPreset);batchPreset.addEventListener('click',()=>{$('#pw-length').value=20;$('#pw-range').value=20;$('#pw-count').value=5;$('#pw-count-range').value=5;['lower','upper','number','symbol'].forEach(key=>{$(`#pw-${key}`).checked=true;});$('#pw-ambiguous').checked=true;generate();});
const wordsPreset=document.createElement('button');wordsPreset.className='st-secondary';wordsPreset.id='pw-words-preset';wordsPreset.type='button';wordsPreset.dataset.ko='단어 조합 만들기';wordsPreset.dataset.en='Generate word phrase';wordsPreset.textContent=tr('단어 조합 만들기','Generate word phrase');batchPreset.after(wordsPreset);wordsPreset.addEventListener('click',()=>{currentCount=Math.max(1,Math.min(20,Number($('#pw-count').value)||1));current=Array.from({length:currentCount},()=>Array.from({length:4},()=>words[random(words.length)]).join('-')+'-'+String(random(90)+10)).join('\n');currentBits=Math.round(4*Math.log2(words.length)+Math.log2(90));$('#pw-result').textContent=current;$('#pw-meter').style.width=`${Math.min(100,Math.round(currentBits/1.2))}%`;$('#pw-copy').disabled=false;$('#pw-fallback').hidden=true;renderDetail();setStatus('created');});
$('#pw-safe-preset').addEventListener('click',()=>{$('#pw-length').value=20;$('#pw-range').value=20;$('#pw-count').value=1;$('#pw-count-range').value=1;['lower','upper','number','symbol'].forEach(key=>{$(`#pw-${key}`).checked=true;});$('#pw-ambiguous').checked=true;generate();});
$('#pw-strong-preset').addEventListener('click',()=>{$('#pw-length').value=32;$('#pw-range').value=32;$('#pw-count').value=1;$('#pw-count-range').value=1;['lower','upper','number','symbol'].forEach(key=>{$(`#pw-${key}`).checked=true;});$('#pw-ambiguous').checked=true;$('#pw-fallback').hidden=true;generate();});
$('#pw-range').addEventListener('input',()=>{$('#pw-length').value=$('#pw-range').value;generate();});$('#pw-length').addEventListener('change',generate);$('#pw-count-range').addEventListener('input',()=>{$('#pw-count').value=$('#pw-count-range').value;generate();});$('#pw-count').addEventListener('change',generate);document.querySelectorAll('input[type=checkbox]').forEach(input=>input.addEventListener('change',generate));$('#pw-generate').addEventListener('click',generate);$('#pw-copy').addEventListener('click',async()=>{if(!current){setStatus('empty');return;}if(await copyText(current)){setStatus('copied');$('#pw-fallback').hidden=true;}else{$('#pw-fallback').value=current;$('#pw-fallback').hidden=false;setStatus('blocked');}});addEventListener('toolbox-language-change',()=>{renderDetail();renderStatus();});generate();setupEmbedHeight('password-generator',{content:true});
