import {copyText,setupEmbedHeight} from '../../assets/play-tools.js?v=0.3.2';
const $=s=>document.querySelector(s), sets={lower:'abcdefghijklmnopqrstuvwxyz',upper:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',number:'0123456789',symbol:'!@#$%^&*()-_=+[]{};:,.?'};
const tr=(ko,en)=>window.ToolboxI18n?.language==='en'?en:ko;let current='',currentBits=0,statusState='created';
function random(max){const limit=256-256%max,buffer=new Uint8Array(1);do{crypto.getRandomValues(buffer);}while(buffer[0]>=limit);return buffer[0]%max;}
function shuffle(text){const out=[...text];for(let i=out.length-1;i>0;i--){const j=random(i+1);[out[i],out[j]]=[out[j],out[i]];}return out.join('');}
function selected(){return Object.keys(sets).filter(key=>$(`#pw-${key}`).checked).map(key=>sets[key]).map(text=>$('#pw-ambiguous').checked?text.replace(/[0OlI]/g,''):text);}
function renderDetail(){if(!current){$('#pw-detail').textContent='';return;}$('#pw-detail').textContent=tr(`예상 조합 강도 약 ${currentBits}비트 · 비밀번호는 서버로 전송되지 않습니다.`,`Estimated combination strength: about ${currentBits} bits · The password never leaves this browser.`);}
function renderStatus(){const states={created:[tr('새 비밀번호를 만들었습니다.','Created a new password.'),'is-good'],groups:[tr('포함할 문자를 하나 이상 선택해 주세요.','Select at least one character group.'),'is-error'],empty:[tr('먼저 비밀번호를 만들어 주세요.','Create a password first.'),'is-error'],copied:[tr('비밀번호를 복사했습니다.','Password copied.'),'is-good'],blocked:[tr('자동 복사가 차단되었습니다. 아래 결과를 선택해 직접 복사해 주세요.','Automatic copying was blocked. Select the result below and copy it manually.'),'']};const state=states[statusState]||states.created;$('#pw-status').textContent=state[0];$('#pw-status').className=`st-status ${state[1]}`;}
function setStatus(state){statusState=state;renderStatus();}
function clearResult(){current='';currentBits=0;$('#pw-result').textContent='';$('#pw-meter').style.width='0%';$('#pw-copy').disabled=true;$('#pw-fallback').hidden=true;renderDetail();}
function generate(){const length=Math.max(8,Math.min(64,Number($('#pw-length').value)||20));$('#pw-length').value=length;$('#pw-range').value=length;const groups=selected();if(!groups.length){clearResult();setStatus('groups');return;}const all=groups.join('');current=shuffle(groups.map(group=>group[random(group.length)]).join('')+Array.from({length:length-groups.length},()=>all[random(all.length)]).join(''));currentBits=Math.round(length*Math.log2(all.length));$('#pw-result').textContent=current;$('#pw-meter').style.width=`${Math.min(100,Math.round(currentBits/1.2))}%`;$('#pw-copy').disabled=false;renderDetail();setStatus('created');$('#pw-fallback').hidden=true;}
$('#pw-range').addEventListener('input',()=>{$('#pw-length').value=$('#pw-range').value;generate();});$('#pw-length').addEventListener('change',generate);document.querySelectorAll('input[type=checkbox]').forEach(input=>input.addEventListener('change',generate));$('#pw-generate').addEventListener('click',generate);$('#pw-copy').addEventListener('click',async()=>{if(!current){setStatus('empty');return;}if(await copyText(current)){setStatus('copied');$('#pw-fallback').hidden=true;}else{$('#pw-fallback').value=current;$('#pw-fallback').hidden=false;window.ToolboxUX?.focusAndSelect($('#pw-fallback'));setStatus('blocked');}});addEventListener('toolbox-language-change',()=>{renderDetail();renderStatus();});generate();setupEmbedHeight('password-generator',{content:true});
