import {copyText,setupEmbedHeight} from '../../assets/play-tools.js?v=0.3.2';
const $=selector=>document.querySelector(selector),tr=(ko,en)=>window.ToolboxI18n?.language==='en'?en:ko;
let resultText='';
const modes={
  of:{labels:[['퍼센트 (%)','Percentage (%)'],['전체값','Total value']],defaults:[15,200]},
  share:{labels:[['부분값','Part value'],['전체값','Total value']],defaults:[30,200]},
  change:{labels:[['이전 값','Previous value'],['새 값','New value']],defaults:[200,230]}
};
function mode(){return document.querySelector('input[name="percent-mode"]:checked').value;}
function number(value){const parsed=Number(value);return Number.isFinite(parsed)&&value.trim()!==''?parsed:null;}
function format(value){return new Intl.NumberFormat(window.ToolboxI18n?.language==='en'?'en-US':'ko-KR',{maximumSignificantDigits:12}).format(value);}
function setStatus(message,error=false){$('#percent-status').textContent=message;$('#percent-status').className=`st-status ${error?'is-error':'is-good'}`;}
function updateLabels(resetValues=false){const current=modes[mode()];$('#percent-a-label').textContent=tr(...current.labels[0]);$('#percent-b-label').textContent=tr(...current.labels[1]);if(resetValues){$('#percent-a').value=current.defaults[0];$('#percent-b').value=current.defaults[1];}calculate();}
function calculate(){const a=number($('#percent-a').value),b=number($('#percent-b').value),current=mode();if(a===null||b===null){resultText='';$('#percent-result').hidden=true;$('#percent-copy').disabled=true;setStatus(tr('두 입력칸에 숫자를 입력해 주세요.','Enter a number in both fields.'),true);return;}if(current==='share'&&b===0||current==='change'&&a===0){resultText='';$('#percent-result').hidden=true;$('#percent-copy').disabled=true;setStatus(tr('나누는 기준값은 0이 될 수 없습니다.','The reference value cannot be zero.'),true);return;}let value,formula,label;if(current==='of'){value=a*b/100;formula=`${format(b)} × ${format(a)} ÷ 100`;label=tr('계산값','Result');}else if(current==='share'){value=a/b*100;formula=`${format(a)} ÷ ${format(b)} × 100`;label=tr('전체에서 차지하는 비율','Share of total');}else{value=(b-a)/Math.abs(a)*100;formula=`(${format(b)} − ${format(a)}) ÷ |${format(a)}| × 100`;label=value>0?tr('증가율','Increase'):value<0?tr('감소율','Decrease'):tr('변화 없음','No change');}const suffix=current==='of'?'':'%',displayValue=current==='change'?Math.abs(value):value;$('#percent-value').textContent=`${label}: ${format(displayValue)}${suffix}`;$('#percent-formula').textContent=formula;resultText=`${$('#percent-value').textContent}\n${formula}`;$('#percent-result').hidden=false;$('#percent-copy').disabled=false;$('#percent-fallback').hidden=true;setStatus(tr('계산을 완료했습니다.','Calculation complete.'));}
document.querySelectorAll('input[name="percent-mode"]').forEach(input=>input.addEventListener('change',()=>updateLabels(true)));$('#percent-calculate').addEventListener('click',calculate);$('#percent-a').addEventListener('input',calculate);$('#percent-b').addEventListener('input',calculate);$('#percent-reset').addEventListener('click',()=>updateLabels(true));$('#percent-copy').addEventListener('click',async()=>{if(!resultText)return;if(await copyText(resultText)){setStatus(tr('계산 결과를 복사했습니다.','Calculation result copied.'));$('#percent-fallback').hidden=true;}else{$('#percent-fallback').value=resultText;$('#percent-fallback').hidden=false;window.ToolboxUX?.focusAndSelect($('#percent-fallback'));setStatus(tr('자동 복사가 차단되었습니다. 아래 결과를 직접 선택해 복사해 주세요.','Automatic copying was blocked. Select the result below and copy it manually.'));}});addEventListener('toolbox-language-change',()=>updateLabels(false));updateLabels(false);setupEmbedHeight('percentage-calculator',{content:true});
