import {copyText,setupEmbedHeight} from '../../assets/play-tools.js?v=0.3.2';
const $=s=>document.querySelector(s),tr=(ko,en)=>window.ToolboxI18n?.language==='en'?en:ko;
let output='';
const escape=value=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function inline(value){let text=escape(value);text=text.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return text.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{const safe=/^(https?:|mailto:)/i.test(url.trim())?escape(url.trim()):'#';return `<a href="${safe}" rel="noopener noreferrer">${label}</a>`;});}
function markdown(source){const lines=source.replace(/\r/g,'').split('\n'),html=[];let code=false,codeLines=[],list=null;const closeList=()=>{if(list){html.push(`</${list}>`);list=null;}};for(const line of lines){if(line.startsWith('```')){closeList();if(code){html.push(`<pre><code>${escape(codeLines.join('\n'))}</code></pre>`);codeLines=[];}code=!code;continue;}if(code){codeLines.push(line);continue;}const heading=line.match(/^(#{1,6})\s+(.+)$/);if(heading){closeList();const level=heading[1].length;html.push(`<h${level}>${inline(heading[2])}</h${level}>`);continue;}const item=line.match(/^\s*([-*]|\d+\.)\s+(.+)$/);if(item){const next=/\d+\./.test(item[1])?'ol':'ul';if(list!==next){closeList();list=next;html.push(`<${list}>`);}html.push(`<li>${inline(item[2])}</li>`);continue;}closeList();if(/^>\s?/.test(line)){html.push(`<blockquote><p>${inline(line.replace(/^>\s?/,''))}</p></blockquote>`);}else if(line.trim())html.push(`<p>${inline(line)}</p>`);}closeList();if(code)html.push(`<pre><code>${escape(codeLines.join('\n'))}</code></pre>`);return html.join('\n');}
function setStatus(message,error=false){$('#md-status').textContent=message;$('#md-status').className=`st-status ${error?'is-error':'is-good'}`;}
function render(){const source=$('#md-input').value;output=markdown(source);$('#md-preview').innerHTML=output||`<p>${tr('미리볼 내용을 입력해 주세요.','Enter Markdown to preview.')}</p>`;$('#md-code').textContent=output;$('#md-words').textContent=(source.trim().match(/\S+/gu)||[]).length.toLocaleString();$('#md-headings').textContent=(source.match(/^#{1,6}\s+.+$/gmu)||[]).length.toLocaleString();$('#md-links').textContent=(source.match(/\[[^\]]+\]\([^)]+\)/g)||[]).length.toLocaleString();setStatus(source.trim()?tr(`마크다운 ${source.length.toLocaleString()}자를 안전한 HTML로 변환했습니다.`,`Converted ${source.length.toLocaleString()} Markdown characters to safe HTML.`):tr('미리볼 마크다운을 입력해 주세요.','Enter Markdown to preview.'));}
let timer;$('#md-input').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(render,120);});
$('#md-copy').addEventListener('click',async()=>{if(!output)return setStatus(tr('복사할 HTML이 없습니다. 먼저 마크다운을 입력해 주세요.','There is no HTML to copy. Enter Markdown first.'),true);if(await copyText(output)){setStatus(tr('HTML을 복사했습니다.','HTML copied.'));$('#md-fallback').hidden=true;}else{$('#md-fallback').value=output;$('#md-fallback').hidden=false;setStatus(tr('자동 복사가 차단되어 직접 복사할 HTML을 표시했습니다.','Automatic copying was blocked. HTML is shown for manual copying.'));}});
$('#md-save').addEventListener('click',()=>{if(!output)return setStatus(tr('저장할 HTML이 없습니다. 먼저 마크다운을 입력해 주세요.','There is no HTML to save. Enter Markdown first.'),true);const blob=new Blob([output],{type:'text/html;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='markdown-result.html';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);setStatus(tr('HTML 파일을 저장했습니다.','HTML file saved.'));});
addEventListener('toolbox-language-change',render);render();setupEmbedHeight('markdown-preview-converter',{content:true});
